Fix -Werror=type-limits in AggregateFunctionTimeSeriesGroupSum.h (size_t() >= 0)
gcc10 reports:

    In file included from ../src/AggregateFunctions/AggregateFunctionTimeSeriesGroupSum.cpp:1:
    ../src/AggregateFunctions/AggregateFunctionTimeSeriesGroupSum.h: In instantiation of ‘void DB::AggregateFunctionTimeSeriesGroupSumData<rate>::add(DB::UInt64, DB::Int64, DB::Float64) [with bool rate = true; DB::UInt64 = long unsigned int; DB::Int64 = long int; DB::Float64 = double]’:
    ../src/AggregateFunctions/AggregateFunctionTimeSeriesGroupSum.h:246:34:   required from ‘void DB::AggregateFunctionTimeSeriesGroupSum<rate>::add(DB::AggregateDataPtr, const DB::IColumn**, size_t, DB::Arena*) const [with bool rate = true; DB::AggregateDataPtr = char*; size_t = long unsigned int]’
    ../src/AggregateFunctions/AggregateFunctionTimeSeriesGroupSum.h:239:10:   required from here
    ../src/AggregateFunctions/AggregateFunctionTimeSeriesGroupSum.h:113:71: error: comparison of unsigned expression in ‘>= 0’ is always true [-Werror=type-limits]
      113 |         while (result[i].first > it_ss->second.dps.front().first && i >= 0)
          |                                                                     ~~^~~~
    ../src/AggregateFunctions/AggregateFunctionTimeSeriesGroupSum.h: In instantiation of ‘void DB::AggregateFunctionTimeSeriesGroupSumData<rate>::add(DB::UInt64, DB::Int64, DB::Float64) [with bool rate = false; DB::UInt64 = long unsigned int; DB::Int64 = long int; DB::Float64 = double]’:
    ../src/AggregateFunctions/AggregateFunctionTimeSeriesGroupSum.h:246:34:   required from ‘void DB::AggregateFunctionTimeSeriesGroupSum<rate>::add(DB::AggregateDataPtr, const DB::IColumn**, size_t, DB::Arena*) const [with bool rate = false; DB::AggregateDataPtr = char*; size_t = long unsigned int]’
    ../src/AggregateFunctions/AggregateFunctionTimeSeriesGroupSum.h:239:10:   required from here
    ../src/AggregateFunctions/AggregateFunctionTimeSeriesGroupSum.h:113:71: error: comparison of unsigned expression in ‘>= 0’ is always true [-Werror=type-limits]