Fix ryu_test compilation (missing <cstring> for memcpy) with libstdc++
libc++ has <cstring> in <string> while libstdc++ does not:

  $ fgrep -r '#include <cstring>' /usr/include/c++/v1/
  /usr/bin/../include/c++/v1/vector:#include <cstring>
  /usr/bin/../include/c++/v1/ext/__hash:#include <cstring>
  /usr/bin/../include/c++/v1/memory:#include <cstring>
  /usr/bin/../include/c++/v1/algorithm:#include <cstring>
  /usr/bin/../include/c++/v1/string:#include <cstring>
  /usr/bin/../include/c++/v1/utility:#include <cstring>

  $ fgrep -r '#include <cstring>' /usr/include/c++/9.2.0/
  /usr/include/c++/9.2.0/experimental/buffer:#include <cstring>
  /usr/include/c++/9.2.0/regex:#include <cstring>
  /usr/include/c++/9.2.0/x86_64-pc-linux-gnu/bits/stdc++.h:#include <cstring>
  /usr/include/c++/9.2.0/x86_64-pc-linux-gnu/32/bits/stdc++.h:#include <cstring>

  $ clang++ -stdlib=libc++ -o /dev/null -c /tmp/test.cpp
  /tmp/test.cpp:7:30: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
          return memcpy(0, 0, 0);
                        ~      ^
  /tmp/test.cpp:7:30: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
          return memcpy(0, 0, 0);
                           ~   ^
  2 warnings generated.

  $ clang++ -o /dev/null -c /tmp/test.cpp
  /tmp/test.cpp:7:16: error: use of undeclared identifier 'memcpy'; did you mean 'wmemcpy'?
          return memcpy(0, 0, 0);
                 ^~~~~~
                 wmemcpy
  /usr/include/wchar.h:262:17: note: 'wmemcpy' declared here
  extern wchar_t *wmemcpy (wchar_t *__restrict __s1,
                  ^
  1 error generated.