Fix usage of static dbms library (add clickhouse_aggregate_functions)
The following error reported:

    FAILED: src/Interpreters/tests/hash_map
    ...
    ld.lld: error: undefined symbol: typeinfo for DB::AggregateFunctionCount
    >>> referenced by typeinfo:308 (../contrib/libcxx/include/typeinfo:308)
    >>>               InterpreterSelectQuery.cpp.o:(std::__1::enable_if<is_pointer_v<DB::AggregateFunctionCount*>, DB::AggregateFunctionCount*>::type typeid_cast<DB::AggregateFunctionCount*, DB::IAggregateFunction>(DB::IAggregateFunction*)) in archive src/libdbms.a
    collect2: error: ld returned 1 exit status

And also this one with gold linker:

  FAILED: programs/clickhouse-odbc-bridge
  ...  src/AggregateFunctions/libclickhouse_aggregate_functions.a ... src/libdbms.a ...
  ../contrib/libcxx/include/typeinfo:308: error: undefined reference to 'typeinfo for DB::AggregateFunctionCount'

Due to order?

Introduced by dd37c466c889c6e736531480ddd61899056e530a/#11661 I guess.