Fix C++20 comparison calls recursively with reversed arguments in UInt128.h (over.match.oper#3.4.4 in gcc10)
Due to [1], gcc10 reports:

    ../src/Common/UInt128.h:92:81: error: in C++20 this comparison calls the current function recursively with reversed arguments [-Werror]
       92 | template <typename T> bool inline operator == (T a, const UInt128 b) { return b == a; }

  [1]: http://eel.is/c++draft/over.match.oper#3.4.4